steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.base', '-t', '$_IMAGE', '.']
images: ['$_IMAGE']
substitutions:
  _IMAGE: us-central1-docker.pkg.dev/videosearch-comparison/videosearch/webapp-base:v1
timeout: 2400s
